sudo: required

language: node_js
node_js:
  - "7"

services:
  - docker

before_install:
  - docker run -d --shm-size=1024m --cap-add=SYS_ADMIN -p=127.0.0.1:4444:4444 yukinying/chrome-headless-browser-selenium
  - npm install

script:
  - npm test
